language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codeclimate-test-reporter

script:
  - flake8 marvin tests
  - pytest --cov=marvin tests/

after_script:
  - codeclimate-test-reporter

jobs:
  include:
    - stage: semantic release
      python: "3.6"
      script: ./bin/semantic-release
