language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install tox
  - pip install flake8

before_script:
  - flake8 marvin tests

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
