language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install tox
  - pip install flake8

before_script:
  - flake8 marvin tests

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)

jobs:
  include:
    - stage: semantic release
      python: "3.5"
      script: ./bin/semantic-release.sh

