
class Events(object):
    SUITE_STARTED = 10
    SUITE_ENDED = 20
    TEST_STARTED = 30
    TEST_ENDED = 40
    STEP_STARTED = 50
    STEP_ENDED = 60
    ALL = [SUITE_STARTED, SUITE_ENDED, TEST_STARTED, TEST_ENDED, STEP_STARTED, STEP_ENDED]